### ISSUE TITLE
Improve error message when running with 'npm run restart' command

### ISSUE THREAD

**Issue by kselveliev** [hashgraph/hedera-local-node#618]
### Problem

Sometimes when I'm running local-node with 'npm run restart -- -d' I'm getting the following error:
<img width="577" alt="image" src="https://github.com/hashgraph/hedera-local-node/assets/138600514/e296c133-a06b-439c-a3d6-46c175ac375c">

Which points me to the port 5600 for grpc, but the reason for failure might be completely different and it is happening in `StartState.ts` `onStart()` method during  `await this.dockerService.dockerComposeUp(this.cliOptions);`

Here is an example reproduce scenario: 
I change my docker-compose.yaml config for prometheus to try and get volumes from my local web3.
```
 prometheus:
    image: prom/prometheus:v2.35.0
    container_name: prometheus
    restart: unless-stopped
    networks:
      - mirror-node
    volumes:
      - ../3/hedera-mirror-node/hedera-mirror-web3/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
```

It now expects that I have created a prometheus.yml file in my web3 module in my mirror-node repo.

But if I've forgotten to add it and try to start local-node I'll get the error:
`[Hedera-Local-Node] ERROR (ConnectionService) connect ECONNREFUSED 127.0.0.1:5600`

Instead of the real error that happens during docker-compose up:
`Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/host_mnt/Users/kristiyanselveliev/hedera/3/hedera-mirror-node/hedera-mirror-web3/prometheus.yml" to rootfs at "/etc/prometheus/prometheus.yml": mount /host_mnt/Users/kristiyanselveliev/hedera/3/hedera-mirror-node/hedera-mirror-web3/prometheus.yml:/etc/prometheus/prometheus.yml (via /proc/self/fd/9), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
`

### Solution

If it is possible, this task is to improve the error messages to be able to get the real reason for failure during docker-compose up when we try to start local-node with 
npm run restart -- -d
